# Redis configuration
# password required from env will be applied via command line argument in compose

# Memory management
maxmemory 256mb
maxmemory-policy allkeys-lru

# Persistence
save 900 1
save 300 10
save 60 10000

# Bind all interfaces
bind 0.0.0.0
protected-mode yes
